### ISSUE TITLE
Negative score values for regression

### ISSUE THREAD

**Issue by saucisson** [cui-unige/mcc4mcc#23] opened 2018-02-21 13:32 UTC
When i run:
```sh
$ ./extract.py
```

The results for regression algorithms are:
```
INFO: Algorithm: decision-tree-regression
INFO:   Min     : -0.23408958008379654
INFO:   Max     : -0.013248075792894998
INFO:   Mean    : -0.10488969127417243
INFO:   Median  : -0.10611363409432173
INFO:   Stdev   : 0.06583227749288169
INFO:   Variance: 0.004333888759899777
INFO: Learning using algorithm: 'knn-regression'.

INFO: Algorithm: knn-regression
INFO:   Min     : -0.10861812564105898
INFO:   Max     : 0.030489299735053432
INFO:   Mean    : -0.04368667835772075
INFO:   Median  : -0.05275172799947181
INFO:   Stdev   : 0.04813321043108172
INFO:   Variance: 0.002316805946402794
INFO: Learning using algorithm: 'random-forest-regression'.

INFO: Algorithm: random-forest-regression
INFO:   Min     : -0.05989802856982962
INFO:   Max     : 0.06089070070317171
INFO:   Mean    : 0.003811517055560587
INFO:   Median  : -0.003230270254699741
INFO:   Stdev   : 0.03777773047303064
INFO:   Variance: 0.0014271569196929476
```

The problem only happens with the option `duplicates=false`.

**Comment by petitgrizzlies** [comment] 2018-02-22 10:16
For the negative score on regression, it's because the regression predict numbers and not classes. So the mean could be negative.

For the classification, I find why the `duplicates=false` kills the accuracy.
By removing the duplicated entries, we change the datas distribution, by changing this distribution, the models doesn't react well.

Can we close this issue ?

**Closed as completed** 2018-02-22 17:11 UTC
Labels: bug
